"""Reviewed sample deck content used by the production seed script.

Each deck points to the primary references used to check its cards.  The
references are deliberately kept with the data so future edits can be audited.
"""


def _deck(title, description, tags, cards, sources, *, sortable=False):
    return {
        "title": title,
        "description": description,
        "tags": tags,
        "sortable": sortable,
        "cards": cards,
        "sources": sources,
    }


MATH_SOURCES = (
    "https://openstax.org/details/books/prealgebra-2e",
    "https://openstax.org/details/books/elementary-algebra-2e",
)

BIOLOGY_SOURCES = (
    "https://openstax.org/details/books/biology-2e",
    "https://www.genome.gov/genetics-glossary",
)

EARTH_SOURCES = (
    "https://science.nasa.gov/solar-system/",
    "https://www.usgs.gov/programs/water-resources/science/water-cycle",
    "https://www.noaa.gov/education/resource-collections/weather-atmosphere",
    "https://www.noaa.gov/education/resource-collections/climate",
)

CIVICS_SOURCES = (
    "https://constitution.congress.gov/constitution/",
    "https://www.usa.gov/branches-of-government",
    "https://www.usa.gov/voting-and-elections",
)

COMPUTING_SOURCES = (
    "https://docs.python.org/3/tutorial/",
    "https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Web_standards",
    "https://git-scm.com/docs/gittutorial",
)


SAMPLE_DECKS = (
    _deck(
        "Arithmetic Essentials",
        "Core number operations, notation, fractions, decimals, and percentages for everyday calculations.",
        "math,arithmetic,numeracy,foundations",
        [
            ("What is the sum in an addition problem?", ("The result of addition",)),
            ("What is the difference in a subtraction problem?", ("The result of subtraction",)),
            ("What is the product in a multiplication problem?", ("The result of multiplication",)),
            ("What is the quotient in a division problem?", ("The result of division",)),
            ("What is the additive identity?", ("0", "zero")),
            ("What is the multiplicative identity?", ("1", "one")),
            ("What does the denominator of a fraction show?", ("The number of equal parts in one whole",)),
            ("What does the numerator of a fraction show?", ("How many equal parts are being considered",)),
            ("How do you convert a decimal to a percent?", ("Multiply by 100 and add the percent sign",)),
            ("How do you convert a percent to a decimal?", ("Divide by 100", "Move the decimal point two places left")),
            ("What is the absolute value of a number?", ("Its distance from zero on the number line",)),
            ("What is a prime number?", ("A whole number greater than 1 with exactly two positive factors",)),
            ("What is a factor?", ("A number that divides another number with no remainder",)),
            ("What does the commutative property allow?", ("Changing the order of addends or factors without changing the result",)),
            ("In standard order of operations, what is evaluated first?", ("Expressions inside grouping symbols", "Grouping symbols")),
        ],
        MATH_SOURCES,
    ),
    _deck(
        "Algebra Foundations",
        "Essential algebra vocabulary and procedures for simplifying and solving linear equations.",
        "math,algebra,equations,foundations",
        [
            ("What is a variable?", ("A symbol that represents a number",)),
            ("What is a coefficient?", ("A number multiplied by a variable",)),
            ("What is a constant term?", ("A term with no variable",)),
            ("What are like terms?", ("Terms with the same variable factors raised to the same powers",)),
            ("What does it mean to evaluate an expression?", ("Substitute values for variables and simplify",)),
            ("What is an equation?", ("A statement that two expressions are equal",)),
            ("What is a solution of an equation?", ("A value that makes the equation true",)),
            ("What is the inverse operation of addition?", ("Subtraction",)),
            ("What is the inverse operation of multiplication?", ("Division",)),
            ("How do you preserve equality while solving an equation?", ("Perform the same operation on both sides",)),
            ("What does the distributive property state?", ("a(b + c) = ab + ac",)),
            ("What is the slope between two points?", ("Change in y divided by change in x", "Rise over run")),
            ("What is the y-intercept of a line?", ("The y-coordinate where the line crosses the y-axis",)),
            ("What is the slope-intercept form of a line?", ("y = mx + b",)),
            ("What does a negative exponent mean for a nonzero base?", ("Take the reciprocal and use the corresponding positive exponent",)),
        ],
        MATH_SOURCES,
    ),
    _deck(
        "Geometry Essentials",
        "Common angle, polygon, circle, area, and volume facts used in introductory geometry.",
        "math,geometry,measurement,formulas",
        [
            ("How many degrees are in a right angle?", ("90 degrees", "90°")),
            ("How many degrees are in a straight angle?", ("180 degrees", "180°")),
            ("What do complementary angles sum to?", ("90 degrees", "90°")),
            ("What do supplementary angles sum to?", ("180 degrees", "180°")),
            ("What is the sum of a triangle's interior angles?", ("180 degrees", "180°")),
            ("What is an equilateral triangle?", ("A triangle with three equal sides",)),
            ("What is an isosceles triangle?", ("A triangle with at least two equal sides",)),
            ("What is the Pythagorean theorem?", ("a² + b² = c² for a right triangle", "a^2 + b^2 = c^2")),
            ("What is the area of a rectangle?", ("length × width", "lw")),
            ("What is the area of a triangle?", ("one-half × base × height", "1/2 bh")),
            ("What is the circumference of a circle?", ("2πr", "πd")),
            ("What is the area of a circle?", ("πr²", "pi times radius squared")),
            ("What is the volume of a rectangular prism?", ("length × width × height", "lwh")),
            ("What is the volume of a cylinder?", ("πr²h",)),
            ("What are congruent figures?", ("Figures with the same size and shape",)),
        ],
        MATH_SOURCES,
    ),
    _deck(
        "Cell Biology",
        "Major cell structures and processes shared across introductory biology courses.",
        "biology,cells,organelles,life-science",
        [
            ("What does the plasma membrane do?", ("Selectively controls movement of substances into and out of the cell",)),
            ("Where is most DNA stored in a eukaryotic cell?", ("The nucleus", "nucleus")),
            ("What is the main function of ribosomes?", ("Protein synthesis", "Make proteins")),
            ("What is the main function of mitochondria?", ("Produce ATP through cellular respiration",)),
            ("What do chloroplasts do?", ("Carry out photosynthesis",)),
            ("What is the function of the Golgi apparatus?", ("Modify, sort, and package proteins and lipids",)),
            ("What does the rough endoplasmic reticulum help produce?", ("Proteins for secretion or membranes",)),
            ("What does the smooth endoplasmic reticulum synthesize?", ("Lipids",)),
            ("What do lysosomes contain?", ("Digestive enzymes",)),
            ("What is the cytosol?", ("The fluid portion of the cytoplasm",)),
            ("What gives plant cells structural support outside the membrane?", ("The cell wall", "cell wall")),
            ("What is diffusion?", ("Net movement from higher concentration to lower concentration",)),
            ("What is osmosis?", ("Diffusion of water across a selectively permeable membrane",)),
            ("What is ATP's primary cellular role?", ("Transfer usable energy for cellular processes",)),
            ("What does cell theory state about new cells?", ("All cells come from preexisting cells",)),
        ],
        BIOLOGY_SOURCES,
    ),
    _deck(
        "Genetics Fundamentals",
        "Key terms for DNA, inheritance, gene expression, and cell division.",
        "biology,genetics,dna,inheritance",
        [
            ("What is a gene?", ("A DNA sequence that contributes to a functional product",)),
            ("What is an allele?", ("An alternative form of a gene",)),
            ("What is a chromosome?", ("A DNA molecule packaged with proteins",)),
            ("What is a genotype?", ("An organism's genetic makeup for the trait being considered",)),
            ("What is a phenotype?", ("An observable trait or characteristic",)),
            ("What does homozygous mean?", ("Having two identical alleles at a gene locus",)),
            ("What does heterozygous mean?", ("Having two different alleles at a gene locus",)),
            ("Which DNA bases pair together?", ("A with T, and C with G", "adenine with thymine, and cytosine with guanine")),
            ("What is DNA replication?", ("The process of copying DNA",)),
            ("What is transcription?", ("Using DNA as a template to make RNA",)),
            ("What is translation?", ("Using an mRNA sequence to build a polypeptide",)),
            ("What is a codon?", ("A three-nucleotide sequence in mRNA that specifies an amino acid or stop signal",)),
            ("What is a mutation?", ("A change in a DNA sequence",)),
            ("What does mitosis produce?", ("Two genetically similar daughter nuclei",)),
            ("What does meiosis produce in humans?", ("Haploid cells that can develop into gametes",)),
        ],
        BIOLOGY_SOURCES,
    ),
    _deck(
        "Human Body Systems",
        "Functions of major organs and organ systems in the human body.",
        "biology,anatomy,physiology,human-body",
        [
            ("What is the circulatory system's main transport organ?", ("The heart", "heart")),
            ("Where does gas exchange occur in the lungs?", ("The alveoli", "alveoli")),
            ("What protein in red blood cells carries oxygen?", ("Hemoglobin", "haemoglobin")),
            ("What is the main function of the small intestine?", ("Digest food and absorb most nutrients",)),
            ("What is a major function of the large intestine?", ("Absorb water and compact feces",)),
            ("What do the kidneys remove from blood?", ("Wastes and excess water",)),
            ("What is the basic functional unit of the kidney?", ("The nephron", "nephron")),
            ("Which organ produces insulin?", ("The pancreas", "pancreas")),
            ("What does insulin generally do to blood glucose?", ("Lowers it by promoting glucose uptake and storage",)),
            ("What is the central nervous system made of?", ("The brain and spinal cord",)),
            ("What connects muscle to bone?", ("A tendon", "tendon")),
            ("What connects bone to bone?", ("A ligament", "ligament")),
            ("What is the largest organ of the human body?", ("The skin", "skin")),
            ("Which immune cells produce antibodies?", ("Plasma cells derived from B cells", "plasma cells")),
            ("What is homeostasis?", ("Maintenance of relatively stable internal conditions",)),
        ],
        BIOLOGY_SOURCES,
    ),
    _deck(
        "Solar System Essentials",
        "The Sun, planets, small bodies, and motions that define our solar system.",
        "earth-space-science,astronomy,space,solar-system,nasa",
        [
            ("What object is at the center of our solar system?", ("The Sun", "Sun")),
            ("Which planet is closest to the Sun?", ("Mercury",)),
            ("Which planet is hottest on average?", ("Venus",)),
            ("Which planet is our home world?", ("Earth",)),
            ("Which planet is called the Red Planet?", ("Mars",)),
            ("Which planet is the largest?", ("Jupiter",)),
            ("Which planet has the most visually prominent ring system?", ("Saturn",)),
            ("Which planet rotates on its side, with an axial tilt near 98 degrees?", ("Uranus",)),
            ("Which major planet is farthest from the Sun?", ("Neptune",)),
            ("What is a dwarf planet beyond Neptune that was once classed as the ninth planet?", ("Pluto",)),
            ("What is the asteroid belt?", ("A region between Mars and Jupiter containing many rocky bodies",)),
            ("What is a comet primarily made of?", ("Ice, dust, and rock",)),
            ("What causes Earth's seasons?", ("Earth's axial tilt as it orbits the Sun",)),
            ("What causes the Moon's phases?", ("Our changing view of its sunlit half as it orbits Earth",)),
            ("What force keeps planets in orbit around the Sun?", ("Gravity",)),
        ],
        EARTH_SOURCES,
        sortable=True,
    ),
    _deck(
        "Earth Systems",
        "Plate tectonics, rocks, water, and the interacting systems of planet Earth.",
        "earth-space-science,geology,water-cycle,plate-tectonics",
        [
            ("What are Earth's four major systems?", ("Geosphere, hydrosphere, atmosphere, and biosphere",)),
            ("What is Earth's outermost solid layer called?", ("The crust", "crust")),
            ("What drives the movement of tectonic plates?", ("Heat-driven motion in Earth's mantle plus gravity-related forces",)),
            ("What happens at a divergent plate boundary?", ("Plates move apart",)),
            ("What happens at a convergent plate boundary?", ("Plates move toward each other",)),
            ("What happens at a transform plate boundary?", ("Plates slide horizontally past each other",)),
            ("What is weathering?", ("Breakdown of rock at or near Earth's surface",)),
            ("What is erosion?", ("Movement of weathered material",)),
            ("How does igneous rock form?", ("Magma or lava cools and solidifies",)),
            ("How does sedimentary rock usually form?", ("Sediments are compacted and cemented",)),
            ("How does metamorphic rock form?", ("Existing rock changes under heat, pressure, or reactive fluids without melting",)),
            ("What is evaporation?", ("Liquid water changes to water vapor",)),
            ("What is condensation?", ("Water vapor changes to liquid water",)),
            ("What is precipitation?", ("Water falls from clouds as rain, snow, sleet, or hail",)),
            ("What is groundwater?", ("Water stored and moving below Earth's surface",)),
        ],
        EARTH_SOURCES,
    ),
    _deck(
        "Weather and Climate",
        "Foundational atmospheric processes, weather measurements, and climate concepts.",
        "earth-space-science,weather,climate,atmosphere",
        [
            ("What is weather?", ("The short-term state of the atmosphere at a time and place",)),
            ("What is climate?", ("The long-term pattern of weather in a region",)),
            ("Which atmospheric layer contains most weather?", ("The troposphere", "troposphere")),
            ("What instrument measures air temperature?", ("A thermometer", "thermometer")),
            ("What instrument measures air pressure?", ("A barometer", "barometer")),
            ("What instrument measures wind speed?", ("An anemometer", "anemometer")),
            ("What does relative humidity compare?", ("Water vapor present with the maximum possible at that temperature",)),
            ("What is the dew point?", ("The temperature at which air becomes saturated with water vapor",)),
            ("What generally happens to rising air?", ("It expands and cools",)),
            ("What is a cold front?", ("The leading edge of an advancing cold air mass",)),
            ("What is a warm front?", ("The leading edge of an advancing warm air mass",)),
            ("Why does wind form?", ("Air moves in response to pressure differences",)),
            ("What powers Earth's water cycle?", ("Energy from the Sun and gravity",)),
            ("What is the greenhouse effect?", ("Atmospheric gases absorb and re-emit heat, warming the surface and lower atmosphere",)),
            ("What is the difference between climate mitigation and adaptation?", ("Mitigation limits climate change; adaptation adjusts to its effects",)),
        ],
        EARTH_SOURCES,
    ),
    _deck(
        "The Constitution and Amendments",
        "Core structure, principles, and selected protections in the U.S. Constitution.",
        "civics,constitution,amendments,united-states",
        [
            ("What are the Constitution's first three words?", ("We the People",)),
            ("What is the supreme law of the United States?", ("The U.S. Constitution", "The Constitution")),
            ("What does Article I establish?", ("The legislative branch", "Congress")),
            ("What does Article II establish?", ("The executive branch",)),
            ("What does Article III establish?", ("The judicial branch",)),
            ("What is federalism?", ("Division of power between the national and state governments",)),
            ("What is separation of powers?", ("Division of government authority among branches",)),
            ("What are checks and balances?", ("Ways each branch can limit the powers of the others",)),
            ("What is the Bill of Rights?", ("The first ten amendments to the Constitution",)),
            ("What does the First Amendment protect?", ("Religion, speech, press, assembly, and petition",)),
            ("What does the Fourth Amendment protect against?", ("Unreasonable searches and seizures",)),
            ("What does the Fifth Amendment include?", ("Due process and protection against compelled self-incrimination",)),
            ("What does the Thirteenth Amendment prohibit?", ("Slavery and involuntary servitude, except as punishment after conviction for a crime",)),
            ("What does the Fourteenth Amendment guarantee to persons?", ("Due process and equal protection under state law",)),
            ("What does the Nineteenth Amendment prohibit in voting?", ("Denying or abridging the vote on account of sex",)),
        ],
        CIVICS_SOURCES,
        sortable=True,
    ),
    _deck(
        "Branches of U.S. Government",
        "Roles and constitutional powers of Congress, the presidency, and the federal courts.",
        "civics,government,congress,presidency,courts",
        [
            ("Which two chambers make up Congress?", ("The House of Representatives and the Senate", "House and Senate")),
            ("How long is a U.S. representative's term?", ("2 years", "two years")),
            ("How long is a U.S. senator's term?", ("6 years", "six years")),
            ("How many senators does each state have?", ("2", "two")),
            ("Which chamber has the sole power of impeachment?", ("The House of Representatives", "House")),
            ("Which chamber tries federal impeachments?", ("The Senate", "Senate")),
            ("Who signs or vetoes bills passed by Congress?", ("The President", "President")),
            ("Who is commander in chief of the armed forces?", ("The President", "President")),
            ("Who nominates federal judges?", ("The President", "President")),
            ("Which body confirms presidential nominations to federal courts?", ("The Senate", "Senate")),
            ("What is judicial review?", ("The power to determine whether government actions conflict with the Constitution",)),
            ("What is the highest federal court?", ("The U.S. Supreme Court", "Supreme Court")),
            ("Which branch interprets federal laws in cases and controversies?", ("The judicial branch",)),
            ("Which branch makes federal laws?", ("The legislative branch", "Congress")),
            ("Which branch enforces federal laws?", ("The executive branch",)),
        ],
        CIVICS_SOURCES,
    ),
    _deck(
        "Voting and Civic Participation",
        "Durable U.S. election concepts and practical ways to participate in civic life.",
        "civics,voting,elections,participation",
        [
            ("What is a primary election?", ("An election used to choose a party's candidate for the general election",)),
            ("What is a general election?", ("An election in which voters choose officeholders",)),
            ("What is a ballot initiative?", ("A proposed law or constitutional change placed before voters",)),
            ("What is a referendum?", ("A vote by the electorate on a law or public question",)),
            ("Who generally administers elections in the United States?", ("State and local election officials",)),
            ("Where should a voter verify registration rules and deadlines?", ("Their official state or local election office",)),
            ("What does the Fifteenth Amendment protect against in voting?", ("Denial or abridgment on account of race, color, or previous condition of servitude",)),
            ("What does the Twenty-Fourth Amendment prohibit in federal elections?", ("Poll taxes", "A poll tax")),
            ("What voting age does the Twenty-Sixth Amendment protect?", ("18 and older", "eighteen and older")),
            ("What is the Electoral College's constitutional role?", ("Selecting the President and Vice President",)),
            ("What is redistricting?", ("Redrawing electoral district boundaries",)),
            ("What is a constituent?", ("A person represented by an elected official",)),
            ("Name a direct way to communicate with an elected official.", ("Call, write, email, or attend a public meeting",)),
            ("What does a trial jury generally decide?", ("The facts of a legal case",)),
            ("Why consult official election sources before voting?", ("Rules, deadlines, locations, and ballot details vary by jurisdiction and election",)),
        ],
        CIVICS_SOURCES,
    ),
    _deck(
        "Python Fundamentals",
        "Core Python syntax and data types for beginning programmers using Python 3.",
        "computing,python,programming,coding",
        [
            ("How do you start a single-line comment in Python?", ("#", "hash sign")),
            ("What built-in function displays output?", ("print()", "print")),
            ("What built-in function reads a line of user input?", ("input()", "input")),
            ("Which keyword defines a function?", ("def",)),
            ("Which keyword begins a conditional branch?", ("if",)),
            ("Which loop iterates over items in an iterable?", ("for loop", "for")),
            ("Which loop repeats while a condition is true?", ("while loop", "while")),
            ("What Python type stores an ordered, mutable sequence?", ("list",)),
            ("What Python type stores an ordered, immutable sequence?", ("tuple",)),
            ("What Python type maps unique keys to values?", ("dict", "dictionary")),
            ("What Python type stores unique elements?", ("set",)),
            ("What are Python's two Boolean values?", ("True and False",)),
            ("What does len() return?", ("The number of items in an object",)),
            ("What does import do?", ("Makes a module's code or names available",)),
            ("How does Python mark a block of code?", ("Indentation",)),
        ],
        COMPUTING_SOURCES,
    ),
    _deck(
        "Web Fundamentals",
        "The essential roles of HTML, CSS, JavaScript, URLs, HTTP, and browser accessibility.",
        "computing,web,html,css,javascript,http",
        [
            ("What is HTML primarily used for?", ("Structuring and giving meaning to web content",)),
            ("What is CSS primarily used for?", ("Styling and laying out web content",)),
            ("What is JavaScript primarily used for in a web page?", ("Programming behavior and interactivity",)),
            ("What does URL stand for?", ("Uniform Resource Locator",)),
            ("What does HTTP stand for?", ("Hypertext Transfer Protocol",)),
            ("What does HTTPS add to HTTP?", ("Encrypted and authenticated transport using TLS",)),
            ("What is a web browser?", ("Software that retrieves and presents web resources",)),
            ("What is a web server?", ("Software or a system that responds to web requests",)),
            ("What does DNS translate domain names into?", ("IP addresses",)),
            ("What is an HTML element?", ("A component represented by tags and its content",)),
            ("What is an HTML attribute?", ("Additional information placed on an element's start tag",)),
            ("What is the DOM?", ("A programming representation of a document as a tree of objects",)),
            ("What does a CSS selector do?", ("Targets elements to receive style rules",)),
            ("Why should images have meaningful alt text when they convey information?", ("To provide a text alternative for users who cannot see the image",)),
            ("Why use semantic HTML?", ("It conveys structure and meaning to browsers and assistive technologies",)),
        ],
        COMPUTING_SOURCES,
    ),
    _deck(
        "Git Essentials",
        "Everyday Git concepts and commands for tracking and sharing source-code changes.",
        "computing,git,version-control,developer-tools",
        [
            ("What is Git?", ("A distributed version control system",)),
            ("What does git init create?", ("A new Git repository",)),
            ("What does git clone do?", ("Creates a local copy of an existing repository",)),
            ("What does git status show?", ("The state of the working tree and staging area",)),
            ("What does git add do?", ("Stages content for the next commit",)),
            ("What does git commit do?", ("Records staged changes as a new commit",)),
            ("What does git diff show by default?", ("Unstaged changes in the working tree",)),
            ("What does git log show?", ("Commit history",)),
            ("What is a Git branch?", ("A movable name pointing to a commit",)),
            ("What does git switch <branch> do?", ("Switches the working tree to that branch",)),
            ("What does git merge do?", ("Integrates changes from another branch or commit",)),
            ("What is a merge conflict?", ("Changes Git cannot combine automatically",)),
            ("What does git fetch do?", ("Downloads refs and objects from a remote without merging them",)),
            ("What does git pull usually do?", ("Fetches from a remote and integrates into the current branch",)),
            ("What does git push do?", ("Updates a remote repository with local refs and objects",)),
        ],
        COMPUTING_SOURCES,
    ),
)


def validate_sample_decks():
    """Fail fast when seed data violates the product's content constraints."""
    if len(SAMPLE_DECKS) != 15:
        raise ValueError("Exactly 15 sample decks are required.")

    titles = set()
    for deck in SAMPLE_DECKS:
        if deck["title"] in titles:
            raise ValueError(f"Duplicate sample deck title: {deck['title']}")
        titles.add(deck["title"])
        if not 15 <= len(deck["cards"]) <= 30:
            raise ValueError(f"{deck['title']} must contain 15-30 cards.")
        if not deck["sources"]:
            raise ValueError(f"{deck['title']} has no fact-check sources.")
        for question, answers in deck["cards"]:
            if not question.strip() or not answers or not all(answer.strip() for answer in answers):
                raise ValueError(f"Invalid card in {deck['title']}: {question!r}")


validate_sample_decks()
