"""add detailed_description and tags to Deck

Revision ID: 045a4c25e1ae
Revises: 074be3b03c53
Create Date: 2026-04-28 18:41:09.336944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045a4c25e1ae'
down_revision = '074be3b03c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detailed_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('detailed_description')

    # ### end Alembic commands ###
