"""add is_public to deck

Revision ID: 074be3b03c53
Revises: c4d5e6f7g8h9
Create Date: 2026-04-28 18:14:02.409905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074be3b03c53'
down_revision = 'c4d5e6f7g8h9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
