"""Add description tags to quiz

Revision ID: 126bfa26887a
Revises: 3ccaa665307b
Create Date: 2026-05-02 00:06:50.331847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126bfa26887a'
down_revision = '3ccaa665307b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
