"""Migrate to deck-based structure with users and multiple answers

Revision ID: 76091e60ff4c
Revises: b2c3d4e5f6a7
Create Date: 2026-03-28 21:52:11.927414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76091e60ff4c'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('username')
    )
    op.create_table('deck',
    sa.Column('deckID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ownedBy', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sortable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ownedBy'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('deckID')
    )
    op.create_table('card',
    sa.Column('cardID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deckID', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deckID'], ['deck.deckID'], ),
    sa.PrimaryKeyConstraint('cardID')
    )
    op.create_table('card_answer',
    sa.Column('answerID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cardID', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cardID'], ['card.cardID'], ),
    sa.PrimaryKeyConstraint('answerID')
    )
    op.drop_table('flash_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flash_card',
    sa.Column('FCid', sa.INTEGER(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), nullable=True),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('answer', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('FCid')
    )
    op.drop_table('card_answer')
    op.drop_table('card')
    op.drop_table('deck')
    op.drop_table('user')
    # ### end Alembic commands ###
